name: "Check Dead Links"

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    # paths-ignore: [ "**.md" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
    # paths-ignore: [ "**.md" ]


jobs:
  crawl_for_broken_links:
    runs-on: ubuntu-latest
    name: "Check for broken links"
    steps:
    - name: Broken-Links-Crawler
      uses: ScholliYT/Broken-Links-Crawler-Action@v3
      with:
        website_url: 'https://microsoft.github.io/SynapseML'
        include_url_prefix: 'https://microsoft.github.io/SynapseML'
        resolve_before_filtering: 'true'
        verbose: 'true'
        max_retry_time: 30
        max_retries: 5
        max_depth: -1
